name: CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:

permissions:
  contents: read

jobs:
  build-npm:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.20.0'
      - name: Install dependencies
        run: npm install
      - name: Generate prisma model
        run: npx prisma generate
      - name: Build
        run: npm run build





